name: ci

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - '*.slurm'
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    strategy:
      matrix:
        variant: [cpu] 
    uses: thewillyP/ReusableWorkflow/.github/workflows/main.yml@main
    with:
      image_name: slurm-queue-server 
      tag: 1.0.${{ github.run_number }}-${{ matrix.variant }}
      build_args: VARIANT=${{ matrix.variant }}  # Pass the variant as a build argument
    secrets: inherit